### ISSUE TITLE
File Auth.pm inside the Simple folder

### ISSUE THREAD

**Issue by ngreis** [Juerd/Net-MQTT-Simple#8]
Hello

On my zoneminder install i installed your Net::MQTT::Simple with CPAN, as the zmNinja author said.
After some debugging i noticed that inside the folder /Simple, there is a file Auth.pm, that as a bug in it.
It references the MQTT protocol version as 0x03, there for causing an error logging with the broker, stating a wrong version.
I have edited that Auth.pm to use your variable $Net::MQTT::Simple::PROTOCOL_LEVEL replacing the 0x03.
Problem solved!
Wanted to do a PR so it would get corrected but the file Auth.pm does not exist on GITHUB or CPAN, so i dont know if the file is "yours" or not.
The author is a Manuel Krenzke, hope this helps.

Best regards

**Comment by mnoorenberghe** [comment]
`Net::MQTT::Simple::Auth` is a separate module not part of this repo but it's no longer necessary since authentication support has since been [added to `Net::MQTT::Simple` itself]( https://github.com/Juerd/Net-MQTT-Simple/blob/cf01b43c27893a07185d4b58ff87db183d08b0e9/Changes#L21-L22).

The issue with zmeventnotification still using `Net::MQTT::Simple::Auth` will be fixed by https://github.com/pliablepixels/zmeventnotification/pull/135

**Comment by Juerd** [comment]
Closing because it's not relevant to this repository.
